helmDefaults:
  wait: true
  timeout: 600
releases:
  - name: travel-agntcy
    namespace: travel-agntcy
    createNamespace: true
    chart: .
    values:
      - values.yaml
      - service:
          type: NodePort
